version: '3.8'
services:
  server:
    build: ./server
    image: python-gcloud-testing
    container_name: pgt-server
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
    volumes:
      - ./.config/gcloud:/app/.config/gcloud
    command: python main.py
    restart: no
